# Example data (generated by chatgpt)
restaurants = [
    {
        "id": 1,
        "name": "Pizza Palace",
        "location": "123 Main Street",
        "image_url": "https://www.example.com/pizza-palace.jpg",
        "menu": [
            {
                "id": 1,
                "name": "Pepperoni Pizza",
                "price": 12.99,
                "image_url": "https://www.example.com/pepperoni-pizza.jpg"
            },
            {
                "id": 2,
                "name": "Margherita Pizza",
                "price": 11.99,
                "image_url": "https://www.example.com/margherita-pizza.jpg"
            },
            {
                "id": 3,
                "name": "BBQ Chicken Pizza",
                "price": 13.99,
                "image_url": "https://www.example.com/bbq-chicken-pizza.jpg"
            }
        ]
    },
    {
        "id": 2,
        "name": "Burger Joint",
        "location": "456 Market Street",
        "image_url": "https://www.example.com/burger-joint.jpg",
        "menu": [
            {
                "id": 4,
                "name": "Cheeseburger",
                "price": 9.99,
                "image_url": "https://www.example.com/cheeseburger.jpg"
            },
                        {
                "id": 5,
                "name": "Bacon Burger",
                "price": 10.99,
                "image_url": "https://www.example.com/bacon-burger.jpg"
            },
            {
                "id": 6,
                "name": "Veggie Burger",
                "price": 8.99,
                "image_url": "https://www.example.com/veggie-burger.jpg"
            }
        ]
    },
    {
        "id": 3,
        "name": "Sushi Spot",
        "location": "789 Ocean Avenue",
        "image_url": "https://www.example.com/sushi-spot.jpg",
        "menu": [
            {
                "id": 7,
                "name": "California Roll",
                "price": 8.99,
                "image_url": "https://www.example.com/california-roll.jpg"
            },
            {
                "id": 8,
                "name": "Spicy Tuna Roll",
                "price": 9.99,
                "image_url": "https://www.example.com/spicy-tuna-roll.jpg"
            },
            {
                "id": 9,
                "name": "Dragon Roll",
                "price": 12.99,
                "image_url": "https://www.example.com/dragon-roll.jpg"
            }
        ]
    },
    {
        "id": 4,
        "name": "Indian Restaurant",
        "location": "321 Curry Street",
        "image_url": "https://www.example.com/indian-restaurant.jpg",
        "menu": [
            {
                "id": 10,
                "name": "Butter Chicken",
                "price": 14.99,
                "image_url": "https://www.example.com/butter-chicken.jpg"
            },
            {
                "id": 11,
                "name": "Palak Paneer",
                "price": 13.99,
                "image_url": "https://www.example.com/palak-paneer.jpg"
            },
            {
                "id": 12,
                "name": "Biryani",
                "price": 12.99,
                "image_url": "https://www.example.com/biryani.jpg"
            }
        ]
    },
    {
        "id": 5,
        "name": "Mexican Grill",
        "location": "654 Taco Boulevard",
        "image_url": "https://www.example.com/mexican-grill.jpg",
        "menu": [
            {
                "id": 13,
                "name": "Beef Tacos",
                "price": 9.99,
                "image_url": "https://www.example.com/beef-tacos.jpg"
            },
            {
                "id": 14,
                "name": "Chicken Burrito",
                                "price": 10.99,
                "image_url": "https://www.example.com/chicken-burrito.jpg"
            },
            {
                "id": 15,
                "name": "Veggie Quesadilla",
                "price": 8.99,
                "image_url": "https://www.example.com/veggie-quesadilla.jpg"
            }
        ]
    },
    {
        "id": 6,
        "name": "Italian Bistro",
        "location": "246 Pasta Place",
        "image_url": "https://www.example.com/italian-bistro.jpg",
        "menu": [
            {
                "id": 16,
                "name": "Spaghetti Bolognese",
                "price": 11.99,
                "image_url": "https://www.example.com/spaghetti-bolognese.jpg"
            },
            {
                "id": 17,
                "name": "Lasagna",
                "price": 13.99,
                "image_url": "https://www.example.com/lasagna.jpg"
            },
            {
                "id": 18,
                "name": "Fettuccine Alfredo",
                "price": 12.99,
                "image_url": "https://www.example.com/fettuccine-alfredo.jpg"
            }
        ]
    },
    {
        "id": 7,
        "name": "Thai Restaurant",
        "location": "159 Noodle Way",
        "image_url": "https://www.example.com/thai-restaurant.jpg",
        "menu": [
            {
                "id": 19,
                "name": "Pad Thai",
                "price": 11.99,
                "image_url": "https://www.example.com/pad-thai.jpg"
            },
            {
                "id": 20,
                "name": "Green Curry",
                "price": 13.99,
                "image_url": "https://www.example.com/green-curry.jpg"
            },
            {
                "id": 21,
                "name": "Red Curry",
                "price": 12.99,
                "image_url": "https://www.example.com/red-curry.jpg"
            }
        ]
    },
    {
        "id": 8,
        "name": "Chinese Takeout",
        "location": "753 Rice Road",
        "image_url": "https://www.example.com/chinese-takeout.jpg",
        "menu": [
            {
                "id": 22,
                "name": "Beef and Broccoli",
                "price": 11.99,
                "image_url": "https://www.example.com/beef-and-broccoli.jpg"
            },
            {
                "id": 23,
                "name": "Kung Pao Chicken",
                "price": 13.99,
                "image_url": "https://www.example.com/kung-pao-chicken.jpg"
            }
        ]
    },
    {
                "id": 9,
        "name": "Deli",
        "location": "951 Sandwich Street",
        "image_url": "https://www.example.com/deli.jpg",
        "menu": [
            {
                "id": 25,
                "name": "Turkey Club",
                "price": 9.99,
                "image_url": "https://www.example.com/turkey-club.jpg"
            },
            {
                "id": 26,
                "name": "Roast Beef",
                "price": 10.99,
                "image_url": "https://www.example.com/roast-beef.jpg"
            },
            {
                "id": 27,
                "name": "Veggie Wrap",
                "price": 8.99,
                "image_url": "https://www.example.com/veggie-wrap.jpg"
            }
        ]
    },
    {
        "id": 10,
        "name": "Bakery",
        "location": "753 Dessert Drive",
        "image_url": "https://www.example.com/bakery.jpg",
        "menu": [
            {
                "id": 28,
                "name": "Chocolate Cake",
                "price": 6.99,
                "image_url": "https://www.example.com/chocolate-cake.jpg"
            },
            {
                "id": 29,
                "name": "Strawberry Cheesecake",
                "price": 7.99,
                "image_url": "https://www.example.com/strawberry-cheesecake.jpg"
            },
            {
                "id": 30,
                "name": "Blueberry Muffins",
                "price": 5.99,
                "image_url": "https://www.example.com/blueberry-muffins.jpg"
            }
        ]
    }
]



locations = [
    {
        "id": 1,
        "name": "Downtown"
    },
    {
        "id": 2,
        "name": "Uptown"
    }
]